services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: proxy
    ports:
      - "80:80"
      - "81:81"  # Admin panel
    volumes:
      - ./letsencrypt:/etc/letsencrypt
  
  apache:
    container_name: apache
    build: ./apache
    restart: unless-stopped
    volumes:
      - ./apache/html:/var/www/html
    ports:
      - "8080:80"

  hold:
    container_name: hold
    image: openresty/openresty
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./hold-backend/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./hold-backend/tmp:/tmp